# Generated by Django 4.2.1 on 2023-05-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
